language: ruby
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - 2.1.0
  - 2.1.9
  - 2.2.0
  - 2.2.5
  - 2.3.0
  - 2.3.1
  - jruby-head
before_install:
  - gem install bundler
  - gem update bundler
