language: ruby
rvm:
- 2.1
- 2.2
- 2.3
- 2.4
- 2.5
- 2.6
- ruby-head
- jruby-19mode
- jruby-head
deploy:
  provider: rubygems
  api_key:
    secure: IXKBqbRf+2aDOpH+g0LpTtIzyagDqjHy6Bo/UYtLqR42CHZUnzre8AvCTvobB+BlHF9W+Igdaf3tzzY+A+XrTf38Iut+zsFI6KnkP7pN8pSMfcpuxZrLi0vd24QAHlHLCHIwsl4WfHj/swIRQGtlhvAV5mcTLW2rhE9/M6pGvRo=
  gem: workpattern
  on:
    tags: true
    repo: callenb/workpattern
