language: ruby
rvm:
  - 1.8.6
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-1.6
  - jruby-1.7
  - jruby-9.1
  - jruby-head
before_install:
  - gem install bundler
  - gem update bundler
